/***************************************************************************
 * RockPod-Lite
 *
 * Original code from RockBox
 * was: apps/mul_id3.h
 * Copyright (C) 2023 Christian Soffke
 *
 * Ported from apps/plugins/lib/mul_id3.h to the core; used only by the
 * core Properties screen (apps/properties.c).
 * GNU General Public License (version 2+)
 *
 * Interface to mul_id3.c and the dir_stats type.
 ****************************************************************************/
#ifndef MUL_ID3_H
#define MUL_ID3_H

#include <stdbool.h>
#include <stdint.h>
#include "file.h"      /* MAX_PATH */
#include "metadata.h"  /* struct mp3entry */

struct dir_stats {
    char dirname[MAX_PATH];
    unsigned int dir_count;
    unsigned int file_count;
    unsigned int audio_file_count;
    unsigned int m3u_file_count;
    unsigned int img_file_count;
    unsigned int vid_file_count;
    unsigned int max_files_in_dir;
    unsigned long long byte_count;
    bool count_all;
    bool canceled;
};

/* create mp3entry that contains matching metadata from multiple tracks */
void collect_id3(struct mp3entry *id3, bool is_first_track);
void finalize_id3(struct mp3entry *id3);

/* Traverse directory, collecting stats/track metadata.
 *
 * 1) If id3_cb is null, dir_properties calculates all dir stats, including the
 * audio file count.
 *
 * 2) If id3_cb points to a function, dir_properties will call it for every audio
 * file encountered, to allow the file's metadata to be collected. The displayed
 * progress bar's maximum value is set to the audio file count.
 * Stats are assumed to have already been generated by a preceding run.
 *
 * If the count_all parameter is set to false, images and videos are not counted,
 * nor is the playlist, image, video or max file in dir count displayed.
 */
bool collect_dir_stats(struct dir_stats *stats, bool (*id3_cb)(const char*));
/* Zero collect_dir_stats()'s persistent progress/throttle state; call once
 * before a fresh top-level scan. */
void collect_dir_stats_reset(void);
void display_dir_stats(struct dir_stats *stats);
unsigned long human_size(unsigned long long byte_count, int32_t *unit_lang_id);

#endif /* MUL_ID3_H */
